openapi: 3.0.0
info:
  title: AI
  version: '1.0'
servers:
  - url: https://api.alcmeon.com
    description: Alcmeon production API server
x-readme:
  explorer-enabled: false

components:

  securitySchemes:
    basic_auth:
      $ref: 'shared-security.yaml#/components/securitySchemes/basic_auth'
    bearer_token:
      $ref: 'shared-security.yaml#/components/securitySchemes/bearer_token'

  schemas:
    ResponseError:
      type: object
      properties:
        error:
          type: string
          description: A short string explaining the reason of the error.
        details:
          type: string
          description: >
            A short string which describes what is wrong. Provide this string to 
            support@alcmeon.com if you wish to obtain more details about the problem.
    SuggestionFinished:
      required: [suggest_answer]
      properties:
        suggest_answer:
          type: object
          required: [id, answer, status]
          properties:
            id:
              type: string
              description: >
                A unique identifier of the generated suggestion.
            answer:
              type: string
              nullable: true
              description: >
                The generated response content to send to the support agent.
            status:
              type: string
              enum: [finished]
              description: >
                Status of the suggestion
                - Should be finished if suggestion was found
            created_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of creation of suggestion.
            finished_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of resolution of suggestion.
            knowledge_documents:
              type: array
              nullable: true
              description: >
                The knowledge documents used to generate the suggestion.
                It can be empty if no documents was used.
              items:
                type: object
                required:
                  - title
                properties:
                  title:
                    type: string
                    description: The tile of the knowledge document.
                  url:
                    type: string
                    format: date-time
                    description: The url of the knowledge document. It can be empty if the document doesn't have a public url (PDF, snippet...).
      example:
        suggest_answer:
          id: "1234"
          answer: "This is my answer"
          status: "finished"
          created_at: "2024-01-22 13:05:21"
          finished_at: "2024-01-22 13:05:41"

    SuggestionFailed:
      required: [suggest_answer]
      properties:
        suggest_answer:
          type: object
          required: [id, error, status]
          properties:
            id:
              type: string
              description: >
                A unique identifier of the generated suggestion.
            error:
              type: string
              nullable: true
              description: >
                The error to send to the support agent.
            status:
              type: string
              enum: [failed]
              description: >
                Status of the suggestion
                - Should be failed if suggestion could not be found
            created_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of creation of suggestion.
            finished_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of resolution of suggestion.            
      example:
        suggest_answer:
          id: "1234"
          error: "Can't generate answer"
          status: "failed"
          created_at: "2024-01-22 13:05:21"
          finished_at: "2024-01-22 13:05:41"
    
    SummaryFinished:
      required: [summarize]
      properties:
        suggest_answer:
          type: object
          required: [id, summary, status]
          properties:
            id:
              type: string
              description: >
                A unique identifier of the generated summary.
            summary:
              type: string
              nullable: true
              description: >
                The generated summary content to send to the support agent.
            status:
              type: string
              enum: [finished]
              description: >
                Status of the summary
                - Should be finished if summary was found
            created_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of creation of summary.
            finished_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of resolution of summary.
            error:
              type: string
              nullable: true
              description: >
                The error to send to the support agent.
            user_summary:
              type: string
            agent_summary:
              type: string
            hashtags:
              type: string
            topic:
              type: string
            sentiment:
              type: string
            original_language:
              type: string
            original_language_name:
              type: string
      example:
        summarize:
          id: "1234"
          summary: "The user requested clarifications about opening hours of the shops and now has asked a question about his loyalty card"
          status: "finished"
          created_at: "2024-01-22 13:05:21"
          finished_at: "2024-01-22 13:05:41"
          
    SummaryFailed:
      required: [summarize]
      properties:
        summarize:
          type: object
          required: [id, error, status]
          properties:
            id:
              type: string
              description: >
                A unique identifier of the generated summary.
            error:
              type: string
              nullable: true
              description: >
                The error to send to the support agent.
            status:
              type: string
              enum: [failed]
              description: >
                Status of the summary
                - Should be failed if summary could not be generated
            created_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of creation of summary.
            finished_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of resolution of summary.            
      example:
        summarize:
          id: "1234"
          error: "Can't generate summary"
          status: "failed"
          created_at: "2024-01-22 13:05:21"
          finished_at: "2024-01-22 13:05:41"
          
    TranslationFinished:
      required: [translate]
      properties:
        translation:
          type: object
          required: [id, translation, status]
          properties:
            id:
              type: string
              description: >
                A unique identifier of the generated translation.
            translation:
              type: string
              nullable: true
              description: >
                DEPRECATED, DO NOT USE - The generated translation content to send to the support agent.
            translation_type:
              type: string
              nullable: true
              description: >
                TEXT or CONVERSATION
            translated_conversation:
              type: string
              nullable: true
              description: >
                The generated translated conversation content to send to the support agent.
            translated_text:
              type: string
              nullable: true
              description: >
                The generated translated text content to send to the support agent.
            status:
              type: string
              enum: [finished]
              description: >
                Status of the translation
                - Should be finished if translation was found
            created_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of creation of translation.
            finished_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of resolution of translation.
            error:
              type: string
              nullable: true
              description: >
                The error to send to the support agent.
            original_language:
              type: string
            original_language_name:
              type: string
      example:
        translate:
          id: "1234"
          translated_text: "Je suis là pour vous aider avec votre question complexe. N'hésitez pas à la poser en détail afin que je puisse vous fournir la meilleure réponse possible."
          translation_type: "TEXT"
          translated_conversation: ""
          status: "finished"
          created_at: "2024-01-22 13:05:21"
          finished_at: "2024-01-22 13:05:41"
          
    TranslationFailed:
      required: [translate]
      properties:
        summarize:
          type: object
          required: [id, error, status]
          properties:
            id:
              type: string
              description: >
                A unique identifier of the generated translation.
            error:
              type: string
              nullable: true
              description: >
                The error to send to the support agent.
            status:
              type: string
              enum: [failed]
              description: >
                Status of the translation
                - Should be failed if translation could not be generated
            created_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of creation of translation.
            finished_at:
              type: string
              format: date-time
              nullable: true
              description: >
                The date of resolution of translation.            
      example:
        translate:
          id: "1234"
          error: "Can't generate translation"
          status: "failed"
          created_at: "2024-01-22 13:05:21"
          finished_at: "2024-01-22 13:05:41"
          
security:
  - basic_auth: []
  - bearer_token: []

paths:
  /ai/answer:
    post:
      summary: Send AI generated answer
      description: >
        Endpoint to invoke to send an AI generated answer to a social network user. 
        
        Once your AI API has been asynchronously called by Alcméon with a jwt specific for a given social network user, 
        this endpoint can be invoked (with the jwt previously received) to send the generated answer to this specific social network user.

      parameters:
        - in: header
          name: X-JWT
          schema:
            type: string
            description: The JWT received (e.g. the `jwt` field in the payload of the asynchronous request sent to your AI API). This JWT is valid for 60 seconds and you cannot reuse a JWT received for user A to send an AI generated answer to another user B.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              required: [message]
              properties:
                message:
                  type: object
                  nullable: true
                  description: An object containing information about the generated answer.
                  properties:
                    id:
                      type: string
                      description: >
                        A unique identifier of the generated response.
                    content:
                      type: string
                      description: >
                        The generated response content to send to the social network user.
                    code:
                      type: string
                      enum: [suggestContactEscalation, mustContactEscalation, EndConversation, continueConversation, breakConversation]
                      nullable: true
                      description: >
                        If no code is provided, the exit taken is the success one (AI Answer - no need for advisor)

                        An optional short string that can be filled to indicate that:
                        
                        - the generated answer can be sent but it's suggested to transfer the conversation afterwards to a support agent: `suggestContactEscalation` 
                        
                        - the generated answer should not be sent and the conversation afterwards should be transferred to a support agent: `mustContactEscalation`
                        
                        - the scope of the conversation can neither be handled by the AI nor by a support agent: `EndConversation`
                        
                        - the AI needs further information and ask a question to the clients to continue the conversation: `continueConversation`
                        
                        - the AI identified the content of the conversation and decided to set a variable to use it later in the scenario: `breakConversation`

                    variables:
                      type: object
                      description: >
                         A dictionary of variables to be used later in the scenario.
                error:
                  type: object
                  nullable: true
                  description: Information on the response generation error when the AI did not manage to generate a satisfying answer.
                  properties:
                    code:
                      type: string
                      nullable: true
                      description: >
                        A short string code of the error.
                    details:
                      type: string
                      nullable: true
                      description: >
                        A short string explaining the reason of the error.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ['ok']
        '400':
          description: If the token used to call the endpoint is not valid (or expired) or if the received json
                        does not match with the expected format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

  /ai/suggest-answer:
    post:
      summary: Send AI generated suggestion
      description: >
        Endpoint to invoke to send an AI generated suggestion to a support agent. 
        
        Once your AI API has been asynchronously called by Alcméon with a webhook_token specific for a given conversation and support agent, 
        this endpoint can be invoked (with the token previously received) to send the generated answer to this specific agent.

      parameters:
        - in: header
          name: X-JWT
          schema:
            type: string
            description: The token received (e.g. the `webhook_token` field in the payload of the request sent to your AI API). This token is valid for 60 seconds and you cannot reuse a token received for user A to send an AI generated answer to another user B.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/SuggestionFinished'
                - $ref: '#/components/schemas/SuggestionFailed'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ['ok']
        '400':
          description: If the token used to call the endpoint is not valid (or expired) or if the received json
                        does not match with the expected format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

  /ai/summary:
    post:
        summary: Send AI generated summary
        description: >
              Endpoint to invoke to send an AI generated conversation summary to a support agent. 
              
              Once your AI API has been asynchronously called by Alcméon with a webhook_token specific for a given conversation and support agent, 
              this endpoint can be invoked (with the token previously received) to send the generated summary to this specific agent.
      
        parameters:
          - in: header
            name: X-JWT
            schema:
              type: string
              description: The token received (e.g. the `webhook_token` field in the payload of the request sent to your AI API). This token is valid for 60 seconds and you cannot reuse a token received for user A to send an AI generated summary to another user B.
            required: true
        requestBody:
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/SummaryFinished'
                  - $ref: '#/components/schemas/SummaryFailed'
        responses:
            '200':
              description: Success
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        enum: ['ok']
            '400':
              description: If the token used to call the endpoint is not valid (or expired) or if the received json
                            does not match with the expected format.
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ResponseError'

  /ai/translation:
    post:
      summary: Send AI generated translation
      description: >
            Endpoint to invoke to send an AI generated translation to a support agent. 
            
            Once your AI API has been asynchronously called by Alcméon with a webhook_token specific for a given conversation and support agent, 
            this endpoint can be invoked (with the token previously received) to send the generated translation to this specific agent.
    
      parameters:
        - in: header
          name: X-JWT
          schema:
            type: string
            description: The token received (e.g. the `webhook_token` field in the payload of the request sent to your AI API). This token is valid for 60 seconds and you cannot reuse a token received for user A to send an AI generated translation to another user B.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/TranslationFinished'
                - $ref: '#/components/schemas/TranslationFailed'
      responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                      enum: ['ok']
          '400':
            description: If the token used to call the endpoint is not valid (or expired) or if the received json
                          does not match with the expected format.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ResponseError'
