openapi: 3.0.0
info:
  title: AI Webhooks
  version: '1.0'
x-readme:
  explorer-enabled: false

components:
  schemas:
    HTTPError:
      properties:
        detail:
          type: object
        message:
          type: string
      type: object
    ValidationError:
      properties:
        detail:
          type: object
          properties:
            <location>:
              type: object
              properties:
                <field_name>:
                  type: array
                  items:
                    type: string
        message:
          type: string
      type: object
    ResponseOk:
      type: string
      enum: ['ok']
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    ApiKey:   
      type: apiKey
      in: header      
      name: apiKey

paths:
  /ai-bot:
    post:
      tags:
      - Invoke AI Bot
      summary: Ask for an AI generated answer to sent to a social network user
      description: >
        Webhook to implement to send an AI generated answer to a social network user.
        This webhook can be protected by checking the api key with the value you defined in the bot configuration in AlcmÃ©on.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - query
              - webhook_token
              properties:
                query:
                  type: string
                  description: User query
                context:
                  description: The context of query.
                  type: string
                jwt:
                  type: string
                  description: Token to send with the answer
              example:
                query: "The question"
                jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDU5Mjg3MzYsImV4cCI6MTcwNTkyODc5NiwiY29tcGFueV9pZCI6NCwidXNlcl9pZCI6NywidGFza19pZCI6MzE1fQ.hxv2p7cUG81bCZ5W4sY5ZeYVMVHZtf"
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - status
                properties:
                  id:
                    type: string
                  status:
                    enum:
                    - Acknowledged
          description: Query is acknoledged
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Authentication error
      security:
      - ApiKey: []

  /suggest-answer:
    post:
      tags:
      - Suggest Answer
      summary: Ask for a suggestion answer for a support agent
      description: >
        Webhook to implement to send an AI generated suggestion to a support agent.
        This webhook can be protected by checking the bearer, a jwt that can be decoded with the public key provided when this webhook is declared.
        The token has a validity limit of 60 seconds.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - version
              - question
              - context
              - webhook_token
              properties:
                version:
                  type: string
                  enum:
                    - '1.0'
                  description: Version of the API
                question:
                  type: string
                  description: Last user question
                context:
                  description: The context of the conversation. For performance raison, only the last 100 items are returned.
                  type: array
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                        enum:
                          - bot
                          - adviser
                          - user
                          - system
                        description: Type of context item 
                      content:
                        type: string
                        description: >
                          The content of the item.
                          For `system` item, it's in the form `key=value`, with one of the following keys:

                          - `adviser_lang`: Language used by the agent

                          - `adviser_user_id`: Agent id

                          - `adviser_user_name`: Agent name

                          - `user_id`: User id

                          - `user_external_id`: External user id (depending on the channel)

                          - `user_name`: User name

                          - `user_site_id`: Channel id

                          - `user_site_name`: Channel name

                          - `custom_field_i`: User custom_field_i value, i being the unique id of the custom field.
                          
                      date:
                        type: string
                        format: date-time
                        description: Date of the item creation.
                webhook_token:
                  type: string
              example:
                version: "1.0"
                question: "The question"
                context:
                  - role: "user"
                    content: "The question"
                    date: "2024-01-18 08:25:36"
                  - role: "system"
                    content: "adviser_lang=en"
                    date: "2024-01-22 13:05:41"
                webhook_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDU5Mjg3MzYsImV4cCI6MTcwNTkyODc5NiwiY29tcGFueV9pZCI6NCwidXNlcl9pZCI6NywidGFza19pZCI6MzE1fQ.hxv2p7cUG81bCZ5W4sY5ZeYVMVHZtf"
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - id
                - status
                properties:
                  id:
                    type: string
                  status:
                    enum:
                    - pending
                    - started
                    - finished
                    - failed
          description: Successful response
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Authentication error
      security:
      - BearerAuth: []

  /suggest-stats:
    post:
      tags:
      - Suggest Statistics
      summary: Provide statistics about a suggested answer
      description: 'Provide statistics about a suggested answer'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOk'
          description: Successful response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Validation error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Authentication error
      requestBody:
        content:
          application/json:
            schema:
              required:
              - version
              - question
              - context
              - suggestion
              - suggestion_id
              - status
              properties:
                version:
                  type: string
                  enum:
                    - '1.0'
                  description: Version of the API
                question:
                  type: string
                  description: Last user question
                context:
                  description: The context of the conversation. For performance reason, only the last 100 items are returned.
                  type: array
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                        enum:
                          - bot
                          - adviser
                          - user
                          - system
                        description: Type of context item 
                      content:
                        type: string
                        description: >
                          The content of the item.
                          For `system` item, it's in the form `key=value`, with one of the following keys:

                          - `adviser_lang`: Language used by the agent

                          - `adviser_user_id`: Agent id

                          - `adviser_user_name`: Agent name

                          - `user_id`: User id

                          - `user_external_id`: External user id (depending on the channel)

                          - `user_name`: User name

                          - `user_site_id`: Channel id

                          - `user_site_name`: Channel name

                          - `custom_field_i`: User custom_field_i value, i being the unique id of the custom field.
                          
                      date:
                        type: string
                        format: date-time
                        description: Date of the item creation.
                suggestion:
                  type: string
                  description: AI Generated Suggestion
                suggestion_id:
                  type: string
                  description: id of the generated suggestion
                status:
                  type: string
                  enum:
                  - rejected
                  - accepted
                  - edited
                  description: >
                    Status of the suggestion:

                    - `rejected`: Rejected by the agent

                    - `accepted`: Accepted by the agent and sent directly

                    - `edited`: Accepted by the agent and edited before being sent.

                answer:
                  description: Answer sent by the agent if the suggestion was not rejected.
                  type: string
              example:
                version: "1.0"
                question: "The question"
                context:
                  - role: "user"
                    content: "The question"
                    date: "2024-01-18 08:25:36"
                  - role: "adviser"
                    content: "This is my answer"
                    date: "2024-01-22 13:05:41"
                  - role: "system"
                    content: "adviser_lang=en"
                    date: "2024-01-22 13:05:41"
                suggestion: "This is my answer"
                suggestion_id: "1234"
                status: "accepted"
                answer: "This is my answer"
      security:
      - BearerAuth: []
